import { GalleryImage } from "@/model/GalleryPageDTO";

export const initialImages: GalleryImage[] = [
    {
        id: '1',
        src: '/image-1.webp',
        alt: 'Image 1',
        width: 800,
        height: 600,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 1',
    },
    {
        id: '2',
        src: '/image-2.webp',
        alt: 'Image 2',
        width: 1200,
        height: 900,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 2',
    },
    {
        id: '3',
        src: '/image-3.webp',
        alt: 'Image 3',
        width: 800,
        height: 600,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 3',
    },
    {
        id: '4',
        src: '/image-4.webp',
        alt: 'Image 4',
        width: 1200,
        height: 900,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 4',
    },
    {
        id: '5',
        src: '/image-5.webp',
        alt: 'Image 5',
        width: 800,
        height: 600,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 5',
    },
    {
        id: '6',
        src: '/image-6.webp',
        alt: 'Image 6',
        width: 1200,
        height: 900,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 6',
    },
    {
        id: '7',
        src: '/image-7.webp',
        alt: 'Image 7',
        width: 800,
        height: 600,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 7',
    },
    {
        id: '8',
        src: '/image-8.webp',
        alt: 'Image 8',
        width: 1200,
        height: 900,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 8',
    },
    {
        id: '9',
        src: '/image-9.webp',
        alt: 'Image 9',
        width: 800,
        height: 600,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 9',
    },
    {
        id: '10',
        src: '/image-10.jpeg',
        alt: 'Image 10',
        width: 1200,
        height: 900,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 10',
    },
    {
        id: '11',
        src: '/image-11.jpeg',
        alt: 'Image 11',
        width: 800,
        height: 600,
        aspectRatio: 4 / 3,
        isFeatured: false,
        caption: 'Caption for Image 11',
    },
];